### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/gitfromscratch#6]
The font looks super different to me. Is there a quality field? Like antialiasing or something?

- https://gitfromscratch.pages.dev/branches/sticky-notes-and-paintbrushes#using-a-branch-as-a-paintbrush
- https://thecontextwindow.ai/p/9eec2aac-7393-4d94-8160-e76592db72bc?postPreview=paid&updated=2024-07-11T22%3A09%3A24.032Z&audience=everyone&free_preview=false&freemail=true

<img width="819" alt="image" src="https://github.com/user-attachments/assets/6b0a8050-7e8b-4b21-a459-e39b736bb326">

<img width="728" alt="image" src="https://github.com/user-attachments/assets/b60f2a88-8667-4bfb-beda-3f9d0f473a89">

## Here's the homepage for comparison too:

- https://gitfromscratch.pages.dev vs [blog](https://thecontextwindow.ai/p/9eec2aac-7393-4d94-8160-e76592db72bc?postPreview=paid&updated=2024-07-11T22%3A09%3A24.032Z&audience=everyone&free_preview=false&freemail=true)

<img width="812" alt="image" src="https://github.com/user-attachments/assets/334e0375-c692-4f7a-8b90-a947f7ff2c81">

<img width="733" alt="image" src="https://github.com/user-attachments/assets/d5814140-aeb5-4a0f-8788-dc0acd8c9b6a">

**Comment by WebsByTodd** [comment]
One reason is that they are different fonts 😝 . 

1. Apparently I missed the fact that `Lora` should be the font for headings. 
2. The Spectral font isn't being applied to the body and it's falling back to system "serif".

Also or the body text, the content column width is not the same and the color is not the same. I didn't think it would be a good idea to limit our column width since we have wide tables with images in them. 

Thoughts on the color and column widt?

Substack color: rgb(54, 55, 55)
Our color: rgb(63, 63, 70)

**Comment by nedtwigg** [comment]
I'm inclined to keep our column width but take substack's color.

**Comment by nedtwigg** [comment]
Fixed.
